version: '3.8'

services:
  mongo:
    image: mongo:4.4.5
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - ./mongo/database:/data/db
      - ./mongo/configs:/etc/mongo
    command: --config /etc/mongo/mongod.conf
    ports:
      - 27017:27017
  server:
    image: golang:1.16.3
    depends_on:
      - mongo
    volumes:
      - ./server:/app
    working_dir: /app
    command: go run cmd/main.go
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      MONGO_USERNAME: mongo
      MONGO_PASSWORD: pass
      MONGO_HOST: mongo
      MONGO_PORT: 27017
